name: Node.js CI

env:
  SKIP_ENV_VALIDATION: true
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/ai_readiness_test"
  DIRECT_URL: "postgresql://postgres:postgres@localhost:5432/ai_readiness_test"
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Format check
        run: pnpm run format:check

      - name: Unit tests
        run: pnpm run test

      - name: Build, lint, typecheck
        run: pnpm run build

      - name: Setup database
        run: pnpm run db:push

  playwright-tests:
    runs-on: ubuntu-latest
    # We can run this in parallel with the build job since we're using dev server
    # Removed the "needs: build-and-test" dependency

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ai_readiness_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      # Removed the build step since we're using the dev server

      - name: Setup database
        run: pnpm run db:push

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: pnpm run test:e2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:3000

      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: test-results/
          retention-days: 30
